#!/usr/bin/env python3
"""
Markdown to HTML Formatter
Converts Markdown summaries to styled HTML
"""

import sys
import os
import markdown
from datetime import datetime

def format_to_html(input_file, output_file):
    """Convert Markdown file to styled HTML"""
    
    # Create output directory
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    # Read Markdown file
    with open(input_file, 'r', encoding='utf-8') as f:
        markdown_content = f.read()
    
    print(f"Converting Markdown to HTML: {input_file}")
    
    # Convert Markdown to HTML
    html_content = markdown.markdown(markdown_content)
    
    # Create styled HTML document
    html_document = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video Summary</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            background: #f8f9fa;
        }}
        .container {{
            background: white;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        h1, h2, h3 {{
            color: #2c3e50;
        }}
        h1 {{
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        .meta {{
            color: #6c757d;
            font-size: 0.9em;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 1px solid #dee2e6;
        }}
        ul, ol {{
            margin: 15px 0;
            padding-left: 30px;
        }}
        li {{
            margin: 8px 0;
        }}
        blockquote {{
            border-left: 4px solid #3498db;
            margin: 20px 0;
            padding: 10px 20px;
            background: #f8f9fa;
            border-radius: 0 8px 8px 0;
        }}
        code {{
            background: #f1f2f6;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'Courier New', monospace;
        }}
        pre {{
            background: #f1f2f6;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
        }}
        .footer {{
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            color: #6c757d;
            font-size: 0.9em;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🎥 Video Summary</h1>
        <div class="meta">
            <strong>Generated on:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
        
        <div class="content">
            {html_content}
        </div>
        
        <div class="footer">
            <p>Generated by VidScribe2AI - AI Video Transcription & Summarization</p>
        </div>
    </div>
</body>
</html>
    """
    
    # Save HTML file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html_document)
    
    print(f"HTML file created: {output_file}")

def main():
    if len(sys.argv) != 3:
        print("Usage: python formatter.py <input_file> <output_file>")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    # Check if input file exists
    if not os.path.exists(input_file):
        print(f"Error: Input file does not exist: {input_file}")
        sys.exit(1)
    
    format_to_html(input_file, output_file)

if __name__ == "__main__":
    main()
